awa_security:
    resource: "@AwaSecurityBundle/Controller/"
    type:     annotation

awa_app:
    resource: "@AwaAppBundle/Controller/"
    type:     annotation
    prefix:   /

awa_bussiness:
    resource: "@AwaBussinessBundle/Controller/"
    type:     annotation
    prefix:   admin/

awa_base:
    resource: "@AwaBaseBundle/Controller/"
    type:     annotation
    prefix:   base/

awa_learning:
    resource: "@AwaLearningBundle/Controller/"
    type:     annotation
    prefix:   learn/

awa_user:
    resource: "@AwaUserBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    path:     /login
    defaults: { _controller: AcmeSecurityBundle:Security:login }

login_check:
    path: admin/login_check
    
logout:
    pattern: admin/logout
