_store:
    pattern:  /
    defaults: { _controller: AwaStoreBundle:Store:index }

awa_store:
    resource: "@AwaStoreBundle/Controller/"
    type:     annotation
    prefix:   /

awa_security:
    resource: "@AwaSecurityBundle/Controller/"
    type:     annotation

awa_bussiness:
    resource: "@AwaBussinessBundle/Controller/"
    type:     annotation
    prefix:   admin/

awa_base:
    resource: "@AwaBaseBundle/Controller/"
    type:     annotation
    prefix:   base/

awa_user:
    resource: "@AwaUserBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    path:     /login
    defaults: { _controller: AcmeSecurityBundle:Security:login }

login_check:
    path: admin/login_check
    
logout:
    pattern: admin/logout

sonata:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /sonata_admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /sonata_admin
