security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Awa\UserBundle\Entity\User:
          algorithm:        sha1
          encode_as_base64: false
          iterations:       1
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
          chain:
            providers: [in_memory, administrators]
        in_memory:
            memory:
                users:
                    user:  { password: userpassa, roles: [ 'ROLE_USER','ROLE_ADMIN' ] }
                    admina2: { password: adminpassa, roles: [ 'ROLE_ADMIN' ] }
        administrators:
            entity: { class: AwaUserBundle:User  }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false
        
        login_check:
            pattern:  ^/login_check$
            security: false
        
        demo_login:
            pattern:  ^/demo/secured/login$
            security: false
        

        secured_area_admin:
            pattern:    ^/(admin|/demo/secured|role|store/user)/
            form_login:
                check_path: login_check
                login_path: _awa_login
            logout:
                path:   logout
                target: /
            context: primary_auth 
         
        public_area:
            pattern: ^/(user|store)/
            context: primary_auth 
            anonymous: ~
            
        public_area2:
            pattern: ^/
            context: primary_auth 
            anonymous: ~
            
        #secured_area:
        #    pattern: ^/demo/secured
        #    form_login:
        #        check_path: _security_check
        #        login_path: _demo_login
        #    logout:
        #        path:   _demo_logout
        #        target: _demo
                
            
        
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/user/new, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/user/.*, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
