<?php

namespace Awa\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AwaAppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AwaAppRepository extends EntityRepository
{
}
