<?php

namespace Awa\BussinessBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BussinessCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BussinessCategoryRepository extends EntityRepository
{
}
